#!/usr/bin/env bash
#installs nginx and configures it
sudo apt-get update
sudo apt-get install nginx -y
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo service nginx restart
