#!/usr/bin/env bash
#Installs nginx and adds a custom header
apt-get -y update
apt-get -y install nginx

#creates a copy of the index.html file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#prints hello world as the response
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#deals with redirection
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#deals with 404
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default

#adds a custom header response
host_name=$(hostname)
header='\n\tadd_header X-Served-By "$hostname";\n'
place=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $place ]]; then
    sed -i "23i $header" /etc/nginx/sites-available/default
fi
sudo service nginx restart
