#!/usr/bin/env bash

#instal haproxy
sudo apt-get update
sudo apt-get install -y haproxy

#configuring Ha proxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 525536-web-01 54.87.172.130:80 check
    server 525536-web-02 52.204.105.20:80 check
EOF

#restart haproxy
sudo systemctl restart haproxy

sudo systemctl enable haproxy
