#!/usr/bin/env bash

#instal haproxy
sudo apt-get update
sudo apt-get install -y haproxy

#configuring Ha proxy
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 525536-web-01 54.87.172.130:80
        server 525536-web-02 52.204.105.20:80
' >> /etc/haproxy/haproxy.cfg

#restart haproxy
sudo systemctl restart haproxy
