#!/usr/bin/env bash
# installs and configures nginx under a new user
apt-get update
apt-get install nginx -y
sed -i 's/user\s\+nginx;/user nginx;/g' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /var/run/nginx
sed -i '/listen\s\+80;/c\    listen 8080;' /etc/nginx/sites-available/default
service nginx start
