#!/usr/bin/env bash
# installs and configures nginx under a new user
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
